import Head from "next/head";
import { Inter } from "@next/font/google";

import styles from "@/styles/Home.module.css";
import { UserInfo } from "@/components/Home";
import { COLORS } from "@/constants";
import Slide from "@/components/Home/Slide";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main
        style={{
          background: COLORS.background,
          color: "white",
          height: "90vh",
          width: "100vw",
          overflow: "hidden",
        }}
      >
        <UserInfo />
      </main>
    </>
  );
}
